### ISSUE TITLE
Get Wind

### ISSUE THREAD

**Issue by Roman-wdesign** [Roman-wdesign/Weather-app#24]
Get Data from openWeather about Wind

**Comment by simonkrizo** [comment]
Hello, can I work on this issue for one of my classes in school?

**Comment by Roman-wdesign** [comment]
Are you ready to be assignee?

**Comment by simonkrizo** [comment]
Sure :)

**Comment by Roman-wdesign** [comment]
Don't forget about [Contributing Guide](https://github.com/Roman-wdesign/Weather-app/blob/main/CONTRIBUTING.md)
