### ISSUE TITLE
Get pressure + humidity

### ISSUE THREAD

**Issue by Roman-wdesign** [Roman-wdesign/Weather-app#25]
Get from openWeather

**Comment by PoplyJakub** [comment]
Hello, I would like to work on this issue. It is for the purpose of a university subject where we have to contribute to a project issue, so I would like to help you with this project. Thank you for the quick response in advance.

**Comment by Roman-wdesign** [comment]
Hello. Like this project? Your star might help it. Okay, let's code. Please, don't forget about [Contributing Guide](https://github.com/Roman-wdesign/Weather-app/blob/main/CONTRIBUTING.md)
